// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: test_proto2.proto

//go:build !protoopaque

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestProto2 struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	D             *float64               `protobuf:"fixed64,1,req,name=d" json:"d,omitempty"`
	F             *float32               `protobuf:"fixed32,2,req,name=f" json:"f,omitempty"`
	I32           *int32                 `protobuf:"varint,3,req,name=i32" json:"i32,omitempty"`
	I64           *int64                 `protobuf:"varint,4,req,name=i64" json:"i64,omitempty"`
	U32           *uint32                `protobuf:"varint,5,opt,name=u32" json:"u32,omitempty"`
	U64           *uint64                `protobuf:"varint,6,opt,name=u64" json:"u64,omitempty"`
	T             *bool                  `protobuf:"varint,7,opt,name=t" json:"t,omitempty"`
	B             []byte                 `protobuf:"bytes,8,opt,name=b" json:"b,omitempty"`
	S             *string                `protobuf:"bytes,9,opt,name=s" json:"s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestProto2) Reset() {
	*x = TestProto2{}
	mi := &file_test_proto2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestProto2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProto2) ProtoMessage() {}

func (x *TestProto2) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TestProto2) GetD() float64 {
	if x != nil && x.D != nil {
		return *x.D
	}
	return 0
}

func (x *TestProto2) GetF() float32 {
	if x != nil && x.F != nil {
		return *x.F
	}
	return 0
}

func (x *TestProto2) GetI32() int32 {
	if x != nil && x.I32 != nil {
		return *x.I32
	}
	return 0
}

func (x *TestProto2) GetI64() int64 {
	if x != nil && x.I64 != nil {
		return *x.I64
	}
	return 0
}

func (x *TestProto2) GetU32() uint32 {
	if x != nil && x.U32 != nil {
		return *x.U32
	}
	return 0
}

func (x *TestProto2) GetU64() uint64 {
	if x != nil && x.U64 != nil {
		return *x.U64
	}
	return 0
}

func (x *TestProto2) GetT() bool {
	if x != nil && x.T != nil {
		return *x.T
	}
	return false
}

func (x *TestProto2) GetB() []byte {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *TestProto2) GetS() string {
	if x != nil && x.S != nil {
		return *x.S
	}
	return ""
}

func (x *TestProto2) SetD(v float64) {
	x.D = &v
}

func (x *TestProto2) SetF(v float32) {
	x.F = &v
}

func (x *TestProto2) SetI32(v int32) {
	x.I32 = &v
}

func (x *TestProto2) SetI64(v int64) {
	x.I64 = &v
}

func (x *TestProto2) SetU32(v uint32) {
	x.U32 = &v
}

func (x *TestProto2) SetU64(v uint64) {
	x.U64 = &v
}

func (x *TestProto2) SetT(v bool) {
	x.T = &v
}

func (x *TestProto2) SetB(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.B = v
}

func (x *TestProto2) SetS(v string) {
	x.S = &v
}

func (x *TestProto2) HasD() bool {
	if x == nil {
		return false
	}
	return x.D != nil
}

func (x *TestProto2) HasF() bool {
	if x == nil {
		return false
	}
	return x.F != nil
}

func (x *TestProto2) HasI32() bool {
	if x == nil {
		return false
	}
	return x.I32 != nil
}

func (x *TestProto2) HasI64() bool {
	if x == nil {
		return false
	}
	return x.I64 != nil
}

func (x *TestProto2) HasU32() bool {
	if x == nil {
		return false
	}
	return x.U32 != nil
}

func (x *TestProto2) HasU64() bool {
	if x == nil {
		return false
	}
	return x.U64 != nil
}

func (x *TestProto2) HasT() bool {
	if x == nil {
		return false
	}
	return x.T != nil
}

func (x *TestProto2) HasB() bool {
	if x == nil {
		return false
	}
	return x.B != nil
}

func (x *TestProto2) HasS() bool {
	if x == nil {
		return false
	}
	return x.S != nil
}

func (x *TestProto2) ClearD() {
	x.D = nil
}

func (x *TestProto2) ClearF() {
	x.F = nil
}

func (x *TestProto2) ClearI32() {
	x.I32 = nil
}

func (x *TestProto2) ClearI64() {
	x.I64 = nil
}

func (x *TestProto2) ClearU32() {
	x.U32 = nil
}

func (x *TestProto2) ClearU64() {
	x.U64 = nil
}

func (x *TestProto2) ClearT() {
	x.T = nil
}

func (x *TestProto2) ClearB() {
	x.B = nil
}

func (x *TestProto2) ClearS() {
	x.S = nil
}

type TestProto2_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	D   *float64
	F   *float32
	I32 *int32
	I64 *int64
	U32 *uint32
	U64 *uint64
	T   *bool
	B   []byte
	S   *string
}

func (b0 TestProto2_builder) Build() *TestProto2 {
	m0 := &TestProto2{}
	b, x := &b0, m0
	_, _ = b, x
	x.D = b.D
	x.F = b.F
	x.I32 = b.I32
	x.I64 = b.I64
	x.U32 = b.U32
	x.U64 = b.U64
	x.T = b.T
	x.B = b.B
	x.S = b.S
	return m0
}

var File_test_proto2_proto protoreflect.FileDescriptor

const file_test_proto2_proto_rawDesc = "" +
	"\n" +
	"\x11test_proto2.proto\"\x9a\x01\n" +
	"\n" +
	"TestProto2\x12\f\n" +
	"\x01d\x18\x01 \x02(\x01R\x01d\x12\f\n" +
	"\x01f\x18\x02 \x02(\x02R\x01f\x12\x10\n" +
	"\x03i32\x18\x03 \x02(\x05R\x03i32\x12\x10\n" +
	"\x03i64\x18\x04 \x02(\x03R\x03i64\x12\x10\n" +
	"\x03u32\x18\x05 \x01(\rR\x03u32\x12\x10\n" +
	"\x03u64\x18\x06 \x01(\x04R\x03u64\x12\f\n" +
	"\x01t\x18\a \x01(\bR\x01t\x12\f\n" +
	"\x01b\x18\b \x01(\fR\x01b\x12\f\n" +
	"\x01s\x18\t \x01(\tR\x01sB/Z-github.com/galexrt/protosetter/testdata/proto"

var file_test_proto2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_test_proto2_proto_goTypes = []any{
	(*TestProto2)(nil), // 0: TestProto2
}
var file_test_proto2_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_proto2_proto_init() }
func file_test_proto2_proto_init() {
	if File_test_proto2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto2_proto_rawDesc), len(file_test_proto2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto2_proto_goTypes,
		DependencyIndexes: file_test_proto2_proto_depIdxs,
		MessageInfos:      file_test_proto2_proto_msgTypes,
	}.Build()
	File_test_proto2_proto = out.File
	file_test_proto2_proto_goTypes = nil
	file_test_proto2_proto_depIdxs = nil
}
